// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvho6rnXlBTLnm7SCH4IwMRfKJqAgqP24',
    appId: '1:978547834860:web:eb7472ad4b9770d8cb4ac9',
    messagingSenderId: '978547834860',
    projectId: 'ezbudget-test-3eb45',
    authDomain: 'ezbudget-test-3eb45.firebaseapp.com',
    storageBucket: 'ezbudget-test-3eb45.appspot.com',
    measurementId: 'G-D6RYPWHVV8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_Bl4pC-j79Vsjj6oLwpQCOhuJbXkPv68',
    appId: '1:978547834860:android:620dc543f8a0ebe9cb4ac9',
    messagingSenderId: '978547834860',
    projectId: 'ezbudget-test-3eb45',
    storageBucket: 'ezbudget-test-3eb45.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAljlx3nHgTaNMc8CXUV6YPNXq8ByW6yS0',
    appId: '1:978547834860:ios:63d296c1ed907dedcb4ac9',
    messagingSenderId: '978547834860',
    projectId: 'ezbudget-test-3eb45',
    storageBucket: 'ezbudget-test-3eb45.appspot.com',
    iosBundleId: 'com.example.easybudget',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAljlx3nHgTaNMc8CXUV6YPNXq8ByW6yS0',
    appId: '1:978547834860:ios:63d296c1ed907dedcb4ac9',
    messagingSenderId: '978547834860',
    projectId: 'ezbudget-test-3eb45',
    storageBucket: 'ezbudget-test-3eb45.appspot.com',
    iosBundleId: 'com.example.easybudget',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvho6rnXlBTLnm7SCH4IwMRfKJqAgqP24',
    appId: '1:978547834860:web:f9c61f5b74370ba1cb4ac9',
    messagingSenderId: '978547834860',
    projectId: 'ezbudget-test-3eb45',
    authDomain: 'ezbudget-test-3eb45.firebaseapp.com',
    storageBucket: 'ezbudget-test-3eb45.appspot.com',
    measurementId: 'G-FHRN1HMJ86',
  );
}
