import 'package:easybudget/layout/receipt_layout.dart';
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:flutter/widgets.dart';
import 'package:easybudget/layout/appbar_layout.dart';
import 'package:easybudget/layout/default_layout.dart';
import 'package:easybudget/screen/mypage_screen.dart';
import 'package:easybudget/screen/notification_screen.dart';

import 'package:easybudget/constant/color.dart';

class DropdownMenu extends StatefulWidget { // 카테고리 선택 드롭다운 메뉴 위젯
  const DropdownMenu({Key? key}) : super(key: key);

  @override
  State<DropdownMenu> createState() => _DropdownMenu();
}

class _DropdownMenu extends State<DropdownMenu> {
  final _categories = ['카테고리 선택','교통비', '식비', '도서']; // DB에서 받아오도록
  String? _selectedCat;

  @override
  void initState() {
    super.initState();
    setState(() {
      _selectedCat = _categories[0];
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: DropdownButton(
          value: _selectedCat,
          items: _categories
              .map((e) => DropdownMenuItem(
            value: e,
            child: Text(e),
          ))
              .toList(),
          onChanged: (value) {
            setState(() {
              _selectedCat = value!;
            });
          },
        ),
      ),
    );
  }
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class ReceiptverificationScreen extends StatelessWidget {
  const ReceiptverificationScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return DefaultLayout(
      appbar: AppbarLayout(
        title: '영수증 정보 확인',
        action: [],
      ),
      body: Padding(
        padding: EdgeInsets.symmetric(
          horizontal: 20,
          vertical: 10,
        ),
        child: SingleChildScrollView(
          child: Column(
            children: [
              /*Flexible(
                fit: FlexFit.tight,
                child: _VerificationBox(),
              ),*/
              ReceiptLayout(
                purchased: PurchasedView(perchased: '(수원) 222경기대학교 구내 서점',),
                //address: AddressView(address: '경기 수원시 영통구 광교산로 154-42',),
                address: AddressEdit(existingData: null,),
              ),
            ],
          ),
        ),
      ),
    );
  }
}

class _VerificationBox extends StatelessWidget {
  const _VerificationBox({super.key});

  @override
  Widget build(BuildContext context) {
    return Container( // 상단 바 제외, 전체 컨테이너 -> 구매항목 추가 시 스크롤 필요
      child: Stack(
          children: [
              Positioned( // 전체 프레임
                left: 0.5,
                top: 5,
                child: Container(
                  width: 393,
                  height: 580,
                  clipBehavior: Clip.antiAlias,
                  decoration: BoxDecoration(color: Colors.white),
                  child: Stack(
                    children: [
                      Positioned( // 총 금액 프레임
                        left: 31,
                        top: 490,
                        child: Container(
                          width: 358,
                          padding: const EdgeInsets.only(top: 7, bottom: 11),
                          clipBehavior: Clip.antiAlias,
                          decoration: BoxDecoration(color: Colors.white),
                          child: Row(
                            mainAxisSize: MainAxisSize.min,
                            mainAxisAlignment: MainAxisAlignment.center,
                            crossAxisAlignment: CrossAxisAlignment.start,
                            children: [
                              SizedBox( // 총 금액 텍스트
                                width: 139,
                                height: 28,
                                child: Text(
                                  '총 금액',
                                  style: TextStyle(
                                    color: Colors.black,
                                    fontSize: 17,
                                    fontFamily: 'Inter',
                                    fontWeight: FontWeight.w600,
                                    height: 0.08,
                                    letterSpacing: -0.34,
                                  ),
                                ),
                              ),
                              const SizedBox(width: 50),
                              Container( // 위에 표시된 금액에 sum 연산된 정수 + 빨간색 지정
                                width: 169,
                                height: 32,
                                clipBehavior: Clip.antiAlias,
                                decoration: BoxDecoration(),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned( // 금액 표시란
                        left: 240,
                        top: 400,
                        child: Container(
                          width: 139,
                          height: 68,
                          clipBehavior: Clip.antiAlias,
                          decoration: BoxDecoration(
                            border: Border(
                              left: BorderSide(color: Color(0x000000)),
                              top: BorderSide(color: Color(0x000000)),
                              right: BorderSide(color: Color(0x000000)),
                              bottom: BorderSide(width: 1, color: Color(0xFFD3D3D3)),
                            ),
                          ),
                        ),
                      ),
                      Positioned( // 금액
                        left: 240,
                        top: 355,
                        child: Container(
                          width: 139,
                          height: 40,
                          padding: const EdgeInsets.only(top: 8, left: 29, right: 28, bottom: 8),
                          clipBehavior: Clip.antiAlias,
                          decoration: BoxDecoration(
                            border: Border(
                              left: BorderSide(color: Color(0x000000)),
                              top: BorderSide(color: Color(0x000000)),
                              right: BorderSide(color: Color(0x000000)),
                              bottom: BorderSide(width: 1, color: Color(0xFFD3D3D3)),
                            ),
                          ),
                          child: Row(
                            mainAxisSize: MainAxisSize.min,
                            mainAxisAlignment: MainAxisAlignment.center,
                            crossAxisAlignment: CrossAxisAlignment.center,
                            children: [
                              SizedBox(
                                width: 50,
                                height: 24,
                                child: Text(
                                  '금액',
                                  style: TextStyle(
                                    color: Colors.black,
                                    fontSize: 17,
                                    fontFamily: 'Inter',
                                    fontWeight: FontWeight.w600,
                                    height: 0.08,
                                    letterSpacing: -0.34,
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned( // 수량 표시란
                        left: 160,
                        top: 400,
                        child: Container(
                          width: 80,
                          height: 68,
                          clipBehavior: Clip.antiAlias,
                          decoration: BoxDecoration(
                            border: Border(
                              left: BorderSide(color: Color(0x000000)),
                              top: BorderSide(color: Color(0x000000)),
                              right: BorderSide(color: Color(0x000000)),
                              bottom: BorderSide(width: 1, color: Color(0xFFD3D3D3)),
                            ),
                          ),
                        ),
                      ),
                      Positioned( // 수량
                        left: 161,
                        top: 355,
                        child: Container(
                          width: 80,
                          height: 40,
                          padding: const EdgeInsets.symmetric(vertical: 8),
                          clipBehavior: Clip.antiAlias,
                          decoration: BoxDecoration(
                            border: Border(
                              left: BorderSide(color: Color(0x000000)),
                              top: BorderSide(color: Color(0x000000)),
                              right: BorderSide(color: Color(0x000000)),
                              bottom: BorderSide(width: 1, color: Color(0xFFD3D3D3)),
                            ),
                          ),
                          child: Row(
                            mainAxisSize: MainAxisSize.min,
                            mainAxisAlignment: MainAxisAlignment.center,
                            crossAxisAlignment: CrossAxisAlignment.center,
                            children: [
                              SizedBox(
                                width: 50,
                                height: 24,
                                child: Text(
                                  '수량',
                                  textAlign: TextAlign.center,
                                  style: TextStyle(
                                    color: Colors.black,
                                    fontSize: 17,
                                    fontFamily: 'Inter',
                                    fontWeight: FontWeight.w600,
                                    height: 0.08,
                                    letterSpacing: -0.34,
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned( // 상품명 표시란
                        left: 21,
                        top: 400,
                        child: Container(
                          width: 139,
                          height: 68,
                          clipBehavior: Clip.antiAlias,
                          decoration: BoxDecoration(
                            border: Border(
                              left: BorderSide(color: Color(0x000000)),
                              top: BorderSide(color: Color(0x000000)),
                              right: BorderSide(color: Color(0x000000)),
                              bottom: BorderSide(width: 1, color: Color(0xFFD3D3D3)),
                            ),
                          ),
                        ),
                      ),
                      Positioned( // 상품명
                        left: 22,
                        top: 355,
                        child: Container(
                          width: 139,
                          height: 40,
                          padding: const EdgeInsets.symmetric(vertical: 8),
                          clipBehavior: Clip.antiAlias,
                          decoration: BoxDecoration(
                            border: Border(
                              left: BorderSide(color: Color(0x000000)),
                              top: BorderSide(color: Color(0x000000)),
                              right: BorderSide(color: Color(0x000000)),
                              bottom: BorderSide(width: 1, color: Color(0xFFD3D3D3)),
                            ),
                          ),
                          child: Row(
                            mainAxisSize: MainAxisSize.min,
                            mainAxisAlignment: MainAxisAlignment.center,
                            crossAxisAlignment: CrossAxisAlignment.center,
                            children: [
                              SizedBox(
                                width: 120,
                                height: 24,
                                child: Text(
                                  '상품명',
                                  style: TextStyle(
                                    color: Colors.black,
                                    fontSize: 17,
                                    fontFamily: 'Inter',
                                    fontWeight: FontWeight.w600,
                                    height: 0.08,
                                    letterSpacing: -0.34,
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned( // 카테고리 표시란 -> 드롭다운 메뉴 디자인 필요
                        left: 210,
                        top: 250,
                        child: Container(
                          width: 169,
                          height: 32,
                          clipBehavior: Clip.antiAlias,
                          decoration: BoxDecoration(),
                          child: DropdownMenu(),
                        ),
                      ),
                      Positioned( // 카테고리
                        left: 21,
                        top: 261,
                        child: SizedBox(
                          width: 140,
                          height: 31,
                          child: Text(
                            '카테고리',
                            style: TextStyle(
                              color: Colors.black,
                              fontSize: 17,
                              fontFamily: 'Inter',
                              fontWeight: FontWeight.w600,
                              height: 0.08,
                              letterSpacing: -0.34,
                            ),
                          ),
                        ),
                      ),
                      Positioned( // 거래일시 표시란
                        left: 210,
                        top: 186,
                        child: Container(
                          width: 169,
                          height: 32,
                          clipBehavior: Clip.antiAlias,
                          decoration: BoxDecoration(),
                        ),
                      ),
                      Positioned( // 거래일시
                        left: 21,
                        top: 187,
                        child: SizedBox(
                          width: 140,
                          height: 31,
                          child: Text(
                            '거래 일시',
                            style: TextStyle(
                              color: Colors.black,
                              fontSize: 17,
                              fontFamily: 'Inter',
                              fontWeight: FontWeight.w600,
                              height: 0.08,
                              letterSpacing: -0.34,
                            ),
                          ),
                        ),
                      ),
                      Positioned( // 주소 표시란
                        left: 204,
                        top: 112,
                        child: Container(
                          width: 169,
                          height: 32,
                          clipBehavior: Clip.antiAlias,
                          decoration: BoxDecoration(),
                        ),
                      ),
                      Positioned( // 주소
                        left: 21,
                        top: 113,
                        child: SizedBox(
                          width: 140,
                          height: 31,
                          child: Text(
                            '주소',
                            style: TextStyle(
                              color: Colors.black,
                              fontSize: 17,
                              fontFamily: 'Inter',
                              fontWeight: FontWeight.w600,
                              height: 0.08,
                              letterSpacing: -0.34,
                            ),
                          ),
                        ),
                      ),
                      Positioned( // 구매처 표시란
                        left: 210,
                        top: 38,
                        child: Container(
                          height: 32,
                          padding: const EdgeInsets.only(top: 1, right: 6),
                          clipBehavior: Clip.antiAlias,
                          decoration: BoxDecoration(),
                          child: Row(
                            mainAxisSize: MainAxisSize.min,
                            mainAxisAlignment: MainAxisAlignment.start,
                            crossAxisAlignment: CrossAxisAlignment.center,
                            children: [
                              Container(
                                width: 163,
                                height: 31,
                                clipBehavior: Clip.antiAlias,
                                decoration: BoxDecoration(color: Colors.white),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned( // 구매처
                        left: 21,
                        top: 39,
                        child: SizedBox(
                          width: 140,
                          height: 31,
                          child: Text(
                            '구매처',
                            style: TextStyle(
                              color: Colors.black,
                              fontSize: 17,
                              fontFamily: 'Inter',
                              fontWeight: FontWeight.w600,
                              height: 0.08,
                              letterSpacing: -0.34,
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned( // 등록 버튼 -> 누르면 입력된 데이터가 DB에 추가 -> 쿼리문 필요
                left: 206,
                top: 530,
                child: Container(
                  padding: const EdgeInsets.symmetric(horizontal: 20, vertical: 20),
                  decoration: ShapeDecoration(
                    color: Color(0xFF194BFB),
                    shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(8)),
                    shadows: [
                      BoxShadow(
                        color: Color(0x0C000000),
                        blurRadius: 2,
                        offset: Offset(0, 1),
                        spreadRadius: 0,
                      )
                    ],
                  ),
                  child: Row(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.center,
                    crossAxisAlignment: CrossAxisAlignment.center,
                    children: [
                      Text(
                        '등록',
                        style: TextStyle(
                          color: Colors.white,
                          fontSize: 16,
                          fontFamily: 'Inter',
                          fontWeight: FontWeight.w500,
                          height: 0.09,
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned( // 수정 버튼
                left: 118,
                top: 530,
                child: Container(
                  padding: const EdgeInsets.symmetric(horizontal: 20, vertical: 20),
                  decoration: ShapeDecoration(
                    color: Color(0xFF194BFB),
                    shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(8)),
                    shadows: [
                      BoxShadow(
                        color: Color(0x0C000000),
                        blurRadius: 2,
                        offset: Offset(0, 1),
                        spreadRadius: 0,
                      )
                    ],
                  ),
                  child: Row(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.center,
                    crossAxisAlignment: CrossAxisAlignment.center,
                    children: [
                      Text(
                        '수정',
                        style: TextStyle(
                          color: Colors.white,
                          fontSize: 16,
                          fontFamily: 'Inter',
                          fontWeight: FontWeight.w500,
                          height: 0.09,
                        ),
                      ),
                    ],
                  ),
                ),
              ),
          ],
      ),
    );
  }
}